version: '3.8'

x-app_service: &app_service app
x-database_host: &database_host db
x-database_password: &database_password ${DATABASE_PASSWORD:-password}
x-database_port: &database_port ${DATABASE_PORT:-5432}
x-database_user: &database_user ${DATABASE_USER:-postgres}
x-host_address: &host_address ${HOST_ADDRESS:-localhost}
x-rails_bind: &rails_bind ${RAILS_BIND:-0.0.0.0}
x-rails_env: &rails_env ${RAILS_ENV:-development}
x-rails_port: &rails_port ${RAILS_PORT:-3000}
x-web_port: &web_port ${WEB_PORT:-80}

x-rails_service: &rails_service
  build:
    context: .
    dockerfile: .docker/rails/Dockerfile
    target: dev
  depends_on:
    - db
  environment:
    CHOMP_DATABASE_HOST: *database_host
    CHOMP_DATABASE_PASSWORD: *database_password
    CHOMP_DATABASE_USER: *database_user
    CHOMP_HOST_ADDRESS: *host_address
    RAILS_BIND: *rails_bind
    RAILS_ENV: *rails_env
    RAILS_PORT: *rails_port
  image: chomp-rails
  volumes:
    - .:/var/www/chomp
    - bundler_data:/usr/local/bundle

services:
  app:
    <<: *rails_service
    command: .docker/rails/bin/serve
    container_name: chomp-app
    ports:
      - mode: host
        protocol: tcp
        published: *rails_port
        target: *rails_port

  db:
    container_name: chomp-db
    environment:
      POSTGRES_PASSWORD: *database_password
      POSTGRES_USER: *database_user
    healthcheck:
      interval: 10s
      retries: 5
      test: sh -c "pg_isready -U $${{POSTGRES_USER}}"
      timeout: 5s
    image: postgres:14.1-alpine
    ports:
      - mode: host
        protocol: tcp
        published: *database_port
        target: 5432
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      args:
        APP_SERVICE: *app_service
        HOST_ADDRESS: *host_address
        RAILS_PORT: *rails_port
      context: .
      dockerfile: .docker/nginx/Dockerfile
    command: sh -c "nginx -g 'daemon off;'"
    container_name: chomp-nginx
    depends_on:
      - app
    healthcheck:
      interval: 10s
      retries: 5
      test: sh -c "service nginx status || exit 1"
      timeout: 5s
    ports:
      - mode: host
        protocol: tcp
        published: *web_port
        target: 80

volumes:
  bundler_data:
    name: chomp-bundler-data
  db_data:
    name: chomp-db-data
