name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    uses: aaronmallen/chomp.one/.github/workflows/lint.yml@main
  test:
    uses: aaronmallen/chomp.one/.github/workflows/test.yml@main

